version: 1.0.{build}
skip_tags: true
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    dotnet --version
    dotnet restore ./Money.DataType.sln
build:
  project: ./Money.DataType.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: normal
artifacts:
- path: '**/*.nupkg'  
notifications:
- provider: Email
  to:
  - imathome@zoho.com
  subject: Money.DataType build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  api_key:
    secure: ItSHuBFLNELhkxxGbDFCt5KusjjjrliHzU4k07wkoLeQ7uuqp7V2GY7rnbQ5NTlm
  username:
    secure: 3OB0UEYiuXnj04Mi4R8g4w==
