version: 1.0.{build}
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: ItSHuBFLNELhkxxGbDFCt5KusjjjrliHzU4k07wkoLeQ7uuqp7V2GY7rnbQ5NTlm
  username:
    secure: 3OB0UEYiuXnj04Mi4R8g4w==